# Generated by Django 4.2.16 on 2024-10-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='conversation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
